alias KaizeVotes.CookieStore
alias KaizeVotes.Document
alias KaizeVotes.Html
alias KaizeVotes.Http
alias KaizeVotes.Json
alias KaizeVotes.Login
alias KaizeVotes.Timeout
alias KaizeVotes.Votable
alias KaizeVotes.Vote
alias KaizeVotes.Worker
